server:
  port: 8081

keycloak:
  url: http://localhost:8080
  realm: test

spring:
  data:
    mongodb:
      authentication-database: admin
      database: petstore
      uri: mongodb://root:example@localhost:27017/admin?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256

management:
  metrics:
    tags:
      application: pets-backend