spring.application.name=petstore

springfox.documentation.swagger.v2.path=/api-docs
server.contextPath=/v2
server.port=8080
spring.jackson.date-format=net.petstore.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.mvc.pathmatch.matching-strategy=ant-path-matcher


#spring.data.mongodb.uri=mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/petstore
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.uri=mongodb://root:example@localhost:27017/admin?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
spring.data.mongodb.database=petstore