spring.application.name=petstore

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

server.contextPath=/v2
server.port=8080
spring.jackson.date-format=net.petstore.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

spring.data.mongodb.authentication-database=admin
spring.data.mongodb.database=petstore
spring.data.mongodb.uri=mongodb://root:example@localhost:27017/admin?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256

# Keycloak configuration

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/springboot-realm
spring.security.oauth2.client.registration.keycloak.client-id=springboot-app
spring.security.oauth2.client.registration.keycloak.client-secret=YOUR_CLIENT_SECRET # Replace with the secret from Keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/springboot-realm

keycloak.realm=springboot-realm
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=springboot-app
keycloak.credentials.secret=YOUR_CLIENT_SECRET # Replace with the secret from Keycloak
keycloak.security-constraints[0].auth-roles[0]=user
keycloak.security-constraints[0].security-collections[0].patterns[0]=/api/users*