spring.application.name=petstore

springfox.documentation.auto-startup=true
springfox.documentation.swagger.v2.path=/api-docs
server.contextPath=/v2

server.port=8080
spring.jackson.date-format=net.petstore.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.mvc.pathmatch.matching-strategy=ant-path-matcher


spring.redis.host=localhost
spring.redis.timeout=1000